Implementing Azure Trusted signing
velopack/velopack pull request #330
Opened 2024-11-02 22:12 UTC by Keboo

2024-11-07 21:08 UTC, caesay requested changes
Have added some observations - also the tests are failing

2024-11-07 21:08 UTC, caesay commented on src/vpk/Velopack.Packaging.Windows/Commands/WindowsPackCommandRunner.cs
> +            parentDir += "x86";
Shouldn't ever extract x86 because we don't ship an x86 signtool that can use it

2024-11-07 21:08 UTC, caesay commented on src/vpk/Velopack.Packaging/HelperFile.cs
> +        AddSearchPath(AppContext.BaseDirectory, "..", "..", "..", "..", "..", "artwork");
Why have all these paths changed? is that right?

2024-11-07 21:08 UTC, caesay commented on src/vpk/Velopack.Packaging/Velopack.Packaging.csproj
> +    <PackageReference Include="Microsoft.Identity.Client.Broker" Version="4.65.0" />
Duplicated references here, I think this came from a bad rebase maybe?

2024-11-07 21:08 UTC, caesay commented on test/Velopack.Packaging.Tests/TrustedSigningTests.cs
> +        Skip.If(await IsAuthenticatedForCodeSigningAsync());
Should this be `Skip.IfNot`?

2024-11-27 07:09 UTC, caesay approved these changes
I did not run tests (read the commends about az login but wasn't sure exactly what to do) but otherwise I am happy with this PR. Thanks a lot! Feel free to merge when ready.

2024-12-17 09:03 UTC, merged

2025-01-09 09:53 UTC, goswinr commented
Do the docs from April 2024 still apply? https://docs.velopack.io/packaging/signing#azure-trusted-signing or did this change with this PR ?

2025-01-09 10:02 UTC, caesay commented
The docs are up to date. April 2024 refers to when ATS was launched.